### ISSUE TITLE
duplicate media queries

### ISSUE THREAD

**Issue by SummerWish** [dciccale/css2stylus.js#24]
css:

```css
@media screen and (min-width: 450px) {
  .medium-12 {
    width: 100%; }
  .medium-up-1 > .column, .medium-up-1 > .columns {
    width: 100%;
    float: left; }
    .medium-up-1 > .column:nth-of-type(1n), .medium-up-1 > .columns:nth-of-type(1n) {
      clear: none; }
    .medium-up-1 > .column:nth-of-type(1n+1), .medium-up-1 > .columns:nth-of-type(1n+1) {
      clear: both; }
    .medium-up-1 > .column:last-child, .medium-up-1 > .columns:last-child {
      float: left; }
  .medium-collapse > .column, .medium-collapse > .columns {
    padding-left: 0;
    padding-right: 0; }
  .medium-collapse .row,
  .expanded.row .medium-collapse.row {
    margin-left: 0;
    margin-right: 0; }
  .medium-uncollapse > .column, .medium-uncollapse > .columns {
    padding-left: 0.9375rem;
    padding-right: 0.9375rem; }
  .medium-centered {
    float: none;
    margin-left: auto;
    margin-right: auto; }
  .medium-uncentered,
  .medium-push-0,
  .medium-pull-0 {
    position: static;
    margin-left: 0;
    margin-right: 0;
    float: left; } }
```

output:
```stylus
@media screen and (min-width: 450px)
  .medium-12
    width 100%
  .medium-centered
    float none
    margin-left auto
    margin-right auto

@media screen and (min-width: 450px)   .medium-up-1 > .column, .medium-up-1 > .columns
  width 100%
  float left

@media screen and (min-width: 450px)     .medium-up-1 > .column:nth-of-type(1n), .medium-up-1 > .columns:nth-of-type(1n)
  clear none

@media screen and (min-width: 450px)     .medium-up-1 > .column:nth-of-type(1n+1), .medium-up-1 > .columns:nth-of-type(1n+1)
  clear both

@media screen and (min-width: 450px)     .medium-up-1 > .column:last-child, .medium-up-1 > .columns:last-child
  float left

@media screen and (min-width: 450px)   .medium-collapse > .column, .medium-collapse > .columns
  padding-left 0
  padding-right 0

.medium-collapse .row,
@media screen and (min-width: 450px)   .expanded.row .medium-collapse.row
  margin-left 0
  margin-right 0

@media screen and (min-width: 450px)   .medium-uncollapse > .column, .medium-uncollapse > .columns
  padding-left 0.9375rem
  padding-right 0.9375rem

.medium-uncentered,
  .medium-push-0,
@media screen and (min-width: 450px)   .medium-pull-0
  position static
  margin-left 0
  margin-right 0
  float left
```

as you can see, media queries are duplicated
