### ISSUE TITLE
-u options not work as expected

### ISSUE THREAD

**Issue by jide123456** [dciccale/css2stylus.js#26]
style.css
```css
.container {
	-webkit-transform: translateY(100px);
	-ms-transform: translateY(100px);
	-o-transform: translateY(100px);
	transform: translateY(100px);
	background: url(./my-nav-img.png);
}
```

run `css2stylus -u -i4`

style.styl
```css
.container
    transform translateY(100px)
    transform translateY(100px)
    background url(./myimg.png)
```

the result of compile, has redundant transform property and img url be changed (my-nav-img.png -> myimg.png)
