### ISSUE TITLE
@media

### ISSUE THREAD

**Issue by JonDum** [dciccale/css2stylus.js#7]
So @media tags aren't rendering so well right now.

input: 
```css
@media only screen and (max-width: 998px) {
  .page.grid {
    padding: 0% 4%;
  }
}
```

output:
```
@media
  only
    screen
      and
        (max-width
          &:
            998px)
              .page.grid {
    padding 0% 4%
```

It looks like the code is treating the spaces as additional selectors because it's getting through to line 109 `selectors = selector.split(/[\s]+/);`

Maybe we should add another check to the `if` statement on line 99 to see if the selector starts with `@media` then process the contents of that block recursively?

The way it is now doing that recursively would require a lot of rewriting. Maybe there's a better way. What are your thoughts?

**Comment by JaKXz** [comment]
I'm seeing this issue as well.

**Comment by dciccale** [comment]
Seems a pretty good fix to do by adding an additional check. Didn't have the time yet to implement it. I will try it whenever I have time for this, please feel free to contribute

**Comment by KyleKing** [comment]
I'm still having this issue as well, given:
```css
@media(min-width:1200px) {
    .timeline>li {
        min-height: 170px;
    }
}
```

Css2stylus outputs:
```stylus
@media(min-width
  &:1200px)
    .timeline>li {
        min-height 170px
```
